# Generated by Django 4.2.4 on 2023-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_uid', models.TextField(max_length=100, primary_key=True, serialize=False)),
                ('product_title', models.TextField(max_length=100)),
                ('product_description', models.TextField(max_length=800)),
                ('users_interested', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cart_items',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='search_queries',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
