# Generated by Django 4.2.4 on 2023-08-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_user_cart_items_user_search_queries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cart_items',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='user',
            name='search_queries',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
