# Generated by Django 4.2.4 on 2023-08-15 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_cart_items_alter_user_search_queries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='product_img_url',
        ),
    ]
