# Generated by Django 4.2.4 on 2023-08-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_product_description_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.TextField(default=0),
        ),
    ]
